apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circuit-breaker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mjxy9/circuit-breaker.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
